export type Member = {
  id: string
  name: string
  email: string
  role: 'Admin' | 'Editor' | 'Viewer'
  joinedAt: string
  avatarUrl: string
}

export const mockMembers: Member[] = [
  {
    id: '1',
    name: 'Subhash Kumar',
    email: 'subhash@example.com',
    role: 'Admin',
    joinedAt: '2024-11-15',
    avatarUrl: 'https://i.pravatar.cc/150?img=1',
  },
  {
    id: '2',
    name: 'Aditi Sharma',
    email: 'aditi.sharma@example.com',
    role: 'Editor',
    joinedAt: '2025-01-02',
    avatarUrl: 'https://i.pravatar.cc/150?img=2',
  },
  {
    id: '3',
    name: 'Rahul Verma',
    email: 'rahulv@example.com',
    role: 'Viewer',
    joinedAt: '2025-03-14',
    avatarUrl: 'https://i.pravatar.cc/150?img=3',
  },
  {
    id: '4',
    name: 'Priya Mehta',
    email: 'priya.mehta@example.com',
    role: 'Editor',
    joinedAt: '2023-12-22',
    avatarUrl: 'https://i.pravatar.cc/150?img=4',
  },
  {
    id: '5',
    name: 'Ravi Tiwari',
    email: 'ravi.tiwari@example.com',
    role: 'Viewer',
    joinedAt: '2024-08-08',
    avatarUrl: 'https://i.pravatar.cc/150?img=5',
  },
  {
    id: '6',
    name: 'Neha Sinha',
    email: 'neha.sinha@example.com',
    role: 'Admin',
    joinedAt: '2025-04-10',
    avatarUrl: 'https://i.pravatar.cc/150?img=6',
  },
  {
    id: '7',
    name: 'Ankit Yadav',
    email: 'ankit.yadav@example.com',
    role: 'Viewer',
    joinedAt: '2024-10-01',
    avatarUrl: 'https://i.pravatar.cc/150?img=7',
  },
  {
    id: '8',
    name: 'Sneha Roy',
    email: 'sneha.roy@example.com',
    role: 'Editor',
    joinedAt: '2025-05-16',
    avatarUrl: 'https://i.pravatar.cc/150?img=8',
  },
  {
    id: '9',
    name: 'Karan Joshi',
    email: 'karan.j@example.com',
    role: 'Admin',
    joinedAt: '2023-07-25',
    avatarUrl: 'https://i.pravatar.cc/150?img=9',
  },
  {
    id: '10',
    name: 'Meera Shah',
    email: 'meera.shah@example.com',
    role: 'Viewer',
    joinedAt: '2024-06-30',
    avatarUrl: 'https://i.pravatar.cc/150?img=10',
  },
  {
    id: '11',
    name: 'Deepak Nair',
    email: 'deepak.nair@example.com',
    role: 'Editor',
    joinedAt: '2024-05-14',
    avatarUrl: 'https://i.pravatar.cc/150?img=11',
  },
  {
    id: '12',
    name: 'Tanya Singh',
    email: 'tanya.singh@example.com',
    role: 'Viewer',
    joinedAt: '2025-02-12',
    avatarUrl: 'https://i.pravatar.cc/150?img=12',
  },
  {
    id: '13',
    name: 'Mohit Chawla',
    email: 'mohit.chawla@example.com',
    role: 'Admin',
    joinedAt: '2024-03-19',
    avatarUrl: 'https://i.pravatar.cc/150?img=13',
  },
  {
    id: '14',
    name: 'Ritika Kaur',
    email: 'ritika.kaur@example.com',
    role: 'Editor',
    joinedAt: '2023-11-09',
    avatarUrl: 'https://i.pravatar.cc/150?img=14',
  },
  {
    id: '15',
    name: 'Sahil Malhotra',
    email: 'sahil.malhotra@example.com',
    role: 'Viewer',
    joinedAt: '2024-01-26',
    avatarUrl: 'https://i.pravatar.cc/150?img=15',
  },
  {
    id: '16',
    name: 'Anjali Rao',
    email: 'anjali.rao@example.com',
    role: 'Admin',
    joinedAt: '2024-09-20',
    avatarUrl: 'https://i.pravatar.cc/150?img=16',
  },
  {
    id: '17',
    name: 'Nikhil Gupta',
    email: 'nikhil.g@example.com',
    role: 'Editor',
    joinedAt: '2024-10-18',
    avatarUrl: 'https://i.pravatar.cc/150?img=17',
  },
  {
    id: '18',
    name: 'Preeti Jain',
    email: 'preeti.jain@example.com',
    role: 'Viewer',
    joinedAt: '2023-09-14',
    avatarUrl: 'https://i.pravatar.cc/150?img=18',
  },
  {
    id: '19',
    name: 'Vikas Pandey',
    email: 'vikas.p@example.com',
    role: 'Admin',
    joinedAt: '2025-06-05',
    avatarUrl: 'https://i.pravatar.cc/150?img=19',
  },
  {
    id: '20',
    name: 'Simran Ahuja',
    email: 'simran.ahuja@example.com',
    role: 'Editor',
    joinedAt: '2024-02-01',
    avatarUrl: 'https://i.pravatar.cc/150?img=20',
  },
]
